name: On Push

on:
  push:

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
      
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset default

      - name: Build tests
        run: cmake --build --preset testing

      - name: Test
        run: ctest --preset testing

      - name: Install
        run: cmake --build --preset install
        

